# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  farm2tablenw:

services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-supp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.supp.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/55a911d26afb56dc2f533a498d85aa270516551bd9e8f363bdbd2fffbbf81e70_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.supp.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/55a911d26afb56dc2f533a498d85aa270516551bd9e8f363bdbd2fffbbf81e70_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/supp.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peersupp
    networks:
      - farm2tablenw

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-logis
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.logis.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1411d04197fa1521fea31a01df9528a05f6dfc04a4722864f3b08f943bf206fe_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.logis.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1411d04197fa1521fea31a01df9528a05f6dfc04a4722864f3b08f943bf206fe_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/logis.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerlogis
    networks:
      - farm2tablenw

  ca2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-manu
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manu.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/028ca0a2aa4bc80e2e3bd002777c7e6a36af4227f139327eaad1ae7b39fe2d35_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.manu.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/028ca0a2aa4bc80e2e3bd002777c7e6a36af4227f139327eaad1ae7b39fe2d35_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/manu.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peermanu
    networks:
      - farm2tablenw

  ca3:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-audi
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.audi.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7d7f4657d53c03774a576c9c0370f9ae510e452861278bfed845a00cabd6daa0_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.audi.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/7d7f4657d53c03774a576c9c0370f9ae510e452861278bfed845a00cabd6daa0_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/audi.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peeraudi
    networks:
      - farm2tablenw


  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - farm2tablenw

  peer0.supp.example.com:
    container_name: peer0.supp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.supp.example.com
    networks:
      - farm2tablenw

  peer1.supp.example.com:
    container_name: peer1.supp.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.supp.example.com
    networks:
      - farm2tablenw

  peer0.logis.example.com:
    container_name: peer0.logis.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.logis.example.com
    networks:
      - farm2tablenw

  peer1.logis.example.com:
    container_name: peer1.logis.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.logis.example.com
    networks:
      - farm2tablenw

  peer0.manu.example.com:
    container_name: peer0.manu.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manu.example.com
    networks:
      - farm2tablenw

  peer1.manu.example.com:
    container_name: peer1.manu.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.manu.example.com
    networks:
      - farm2tablenw

  peer0.audi.example.com:
    container_name: peer0.audi.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.audi.example.com
    networks:
      - farm2tablenw

  peer1.audi.example.com:
    container_name: peer1.audi.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.audi.example.com
    networks:
      - farm2tablenw

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.supp.example.com:7051
      - CORE_PEER_LOCALMSPID=suppMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supp.example.com/peers/peer0.supp.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supp.example.com/peers/peer0.supp.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supp.example.com/peers/peer0.supp.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supp.example.com/users/Admin@supp.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.supp.example.com
      - peer1.supp.example.com
      - peer0.logis.example.com
      - peer1.logis.example.com
      - peer0.manu.example.com
      - peer1.manu.example.com
      - peer0.audi.example.com
      - peer1.audi.example.com
    networks:
      - farm2tablenw

